"""
diagnose_and_fix.py
───────────────────
Run this from your project root to:
1. See exactly what's in your labeled_dataset.csv
2. Attempt to remap US tickers → Indian equivalents
3. Show you exactly what to run next

Usage:
    python diagnose_and_fix.py
"""

import pandas as pd
from pathlib import Path
import json, sys

ROOT        = Path(__file__).parent
LABELED_CSV = ROOT / "data" / "processed" / "labeled_dataset.csv"
RAW_DIR     = ROOT / "data" / "raw"

# ── US → Indian ticker equivalents (for companies listed on both) ─────────────
US_TO_INDIAN = {
    # Tech / IT
    "INFY":  "INFY.NS",
    "WIT":   "WIPRO.NS",
    "HDB":   "HDFCBANK.NS",
    "IBN":   "ICICIBANK.NS",
    "TTM":   "TATAMOTORS.NS",
    "RELI":  "RELIANCE.NS",
    # ADRs
    "VEDL":  "VEDL.NS",
    "RDY":   "DRREDDY.NS",
    "SHG":   "SBIN.NS",
    "WNS":   "WIPRO.NS",
    "AZRE":  "ADANIENT.NS",
    # Common US tickers that may be in your CSV from Finnhub general news
    "AAPL":  None,
    "NVDA":  None,
    "MSFT":  None,
    "GOOGL": None,
    "META":  None,
    "TSLA":  None,
    "AMZN":  None,
    "JPM":   None,
    "NFLX":  None,
    "AMD":   None,
}

def diagnose():
    print("\n" + "="*60)
    print("  ALPHALENS — CSV DIAGNOSTIC")
    print("="*60)

    if not LABELED_CSV.exists():
        print(f"\n❌ labeled_dataset.csv NOT FOUND at:\n   {LABELED_CSV}")
        print("\nYou need to run the full pipeline first:")
        print("  1. python bulk_collect_v3.py")
        print("  2. python src/features/price_labeler.py")
        print("  3. python src/models/impact_model.py")
        return

    df = pd.read_csv(LABELED_CSV)
    df.columns = [c.strip().lower() for c in df.columns]

    print(f"\n✅ CSV found: {LABELED_CSV}")
    print(f"   Rows    : {len(df)}")
    print(f"   Columns : {list(df.columns)}")

    # Ticker column
    ticker_col = None
    for c in ("ticker", "symbol", "related"):
        if c in df.columns:
            ticker_col = c
            break

    if ticker_col:
        tickers = df[ticker_col].dropna().astype(str).str.strip().unique().tolist()
        indian  = [t for t in tickers if t.endswith(".NS") or t.endswith(".BO")]
        us      = [t for t in tickers if not t.endswith(".NS") and not t.endswith(".BO")]
        print(f"\n   Ticker column: '{ticker_col}'")
        print(f"   Total unique tickers : {len(tickers)}")
        print(f"   Indian (.NS/.BO)      : {len(indian)}")
        if indian: print(f"     → {indian[:10]}")
        print(f"   Non-Indian (US etc.) : {len(us)}")
        if us: print(f"     → {us[:15]}")
    else:
        print("\n⚠️  No ticker column found!")

    # Signal column
    if "signal" in df.columns:
        vc = df["signal"].value_counts().to_dict()
        print(f"\n   Signal distribution: {vc}")
    else:
        print("\n⚠️  No 'signal' column — will be generated by API from sentiment")

    # Sentiment
    for col in ("sentiment", "av_sentiment", "_sentiment"):
        if col in df.columns:
            vc = df[col].value_counts().head(6).to_dict()
            print(f"   '{col}' values: {vc}")

    # Label
    if "label" in df.columns:
        vc = df["label"].value_counts().to_dict()
        print(f"   label (price move): {vc}")

    # Return
    for col in ("return_24h", "price_return_24h"):
        if col in df.columns:
            r = df[col].dropna()
            print(f"   '{col}': mean={r.mean():.4f}, non-null={len(r)}")

    print("\n" + "="*60)
    print("  DIAGNOSIS SUMMARY")
    print("="*60)

    if ticker_col and len(indian) > 0:
        print("\n✅ You already have Indian tickers in the CSV!")
        print("   The API should be showing signals.")
        print("   → Restart uvicorn and check http://localhost:8000/debug/csv")
    elif ticker_col and len(us) > 0:
        print("\n⚠️  Your CSV only has US tickers.")
        print("   The Indian sector filter won't match anything.")
        print("\n   OPTION A — Re-collect Indian data (recommended):")
        print("     python bulk_collect_v3.py   ← collects Indian company news")
        print("     python src/features/price_labeler.py")
        print("     python src/models/impact_model.py")
        print("\n   OPTION B — Quick fix: rename US tickers → Indian equivalents")
        print("     python diagnose_and_fix.py --remap")
    else:
        print("\n❌ CSV has no recognizable ticker data.")
        print("   Run the full pipeline from scratch.")

    print()

def remap_tickers():
    """Quick fix: rename any US tickers to Indian equivalents where possible."""
    if not LABELED_CSV.exists():
        print("❌ labeled_dataset.csv not found"); return

    df = pd.read_csv(LABELED_CSV)
    df.columns = [c.strip().lower() for c in df.columns]

    ticker_col = None
    for c in ("ticker", "symbol", "related"):
        if c in df.columns:
            ticker_col = c; break

    if not ticker_col:
        print("❌ No ticker column found"); return

    before = df[ticker_col].value_counts().to_dict()
    df[ticker_col] = df[ticker_col].apply(
        lambda t: US_TO_INDIAN.get(str(t).strip(), t) if US_TO_INDIAN.get(str(t).strip()) else t
    )
    # Rename column to 'ticker'
    df = df.rename(columns={ticker_col: "ticker"})
    df.to_csv(LABELED_CSV, index=False)
    after = df["ticker"].value_counts().to_dict()
    print(f"✅ Remapped {LABELED_CSV.name}")
    print(f"   Before: {list(before.keys())[:8]}")
    print(f"   After:  {list(after.keys())[:8]}")
    print("\n   Now restart uvicorn — Indian tickers will show signals.")

if __name__ == "__main__":
    if "--remap" in sys.argv:
        remap_tickers()
    else:
        diagnose()